"""Cloud cell targets for the owned terminal journey (honua-release#377, #507).

The cloud harness (`e2e/cloud_journey.py`) generates one target document per cell attempt from
the authored local-docker execution fixture, so the journey's fixture has one source. The
document carries references only: environment variable names for the cell's bootstrap
credential, the journey principals and the datasource coordinates. It is retained next to the
receipt, so it must never hold a credential, a database host or a login.

What differs from local Docker, and why:

* Principals are minted at run time through the cell's admin REST API with the cell's bootstrap
  credential, with the same grants and Studio author role as `local_fixture`, and revoked at the
  end of the run (`local_fixture.credentials` / `local_fixture.revoke`).
* The second-tenant principal does not exist on a cell. Local Docker injects an ephemeral JWT
  signing key into its compose stack; a cell trusts no harness-held issuer and admin API keys are
  tenant-independent. The target documents the principal as unavailable, so the tenant-isolation
  assertion is blocked with that reason while the rest of stage 8 runs.
* The datasource is the cell's own RDS database, reached with TLS (`sslRequired`, `Require`).
* A cell is reached through one endpoint. The cross-replica re-read goes through that endpoint and
  the target names the serving topology behind it (ALB across ECS tasks, or one Lambda function).
"""
from __future__ import annotations

import copy
import hashlib
import re
import urllib.parse
from pathlib import Path

import local_fixture

HERE = Path(__file__).resolve().parent
CLOUD_KINDS = local_fixture.CLOUD_KINDS
CELL_ID = re.compile(r"(aws-ecs|aws-serverless)/redis-(on|off)\Z")
ENV_NAME = re.compile(r"[A-Z][A-Z0-9_]{0,127}\Z")
ADMIN_ENV = "HONUA_CLOUD_JOURNEY_ADMIN"
# The bootstrap credential, the cell datasource and nothing else cross into the candidate
# sandbox (pins.CANDIDATE_ENV_ALLOWLIST names exactly these).
DATASOURCE_ENV = {
    "host": "HONUA_JOURNEY_DATASOURCE_HOST",
    "port": "HONUA_JOURNEY_DATASOURCE_PORT",
    "databaseName": "HONUA_JOURNEY_DATASOURCE_DATABASE",
    "username": "HONUA_JOURNEY_DATASOURCE_USERNAME",
    "password": "HONUA_JOURNEY_DATASOURCE_PASSWORD",
}
MINTED_PRINCIPALS = tuple(local_fixture.GRANTS)
TOPOLOGIES = {
    "aws-ecs": {
        "id": "ecs-alb-tasks",
        "description": "the cell load balancer spreads requests across its ECS tasks; "
                       "the re-read is a new request that is not pinned to a different task",
    },
    "aws-serverless": {
        "id": "lambda-function",
        "description": "one Lambda function behind its HTTPS function URL; the re-read is a new "
                       "request to any warm or new instance, not a separately addressed replica",
    },
}
OTHER_TENANT_BLOCKER = "https://github.com/honua-io/honua-release/issues/377"
OTHER_TENANT_REASON = (
    "no second-tenant principal exists on a cloud cell: the cell configures no identity issuer the "
    "harness holds a signing key for (local Docker injects an ephemeral Oidc:TokenValidation key) and "
    "admin API keys are tenant-independent, so none is fabricated")
REVISIONS = {
    "fixtureRevision": "terminal-zero-to-map-v1",
    "configRevision": "terminal-profiles-cloud-v1",
    "authPolicyRevision": "terminal-separate-principals-cloud-v1",
}


class TargetError(ValueError):
    pass


def kind_of(cell):
    """The cloud target kind of a cell id, or None when the cell has no cloud target here."""
    match = CELL_ID.match(cell or "")
    return match.group(1) if match else None


def build(template, *, cell, endpoint):
    """The cloud target document for one cell attempt, derived from the authored local fixture."""
    kind = kind_of(cell)
    if kind is None:
        raise TargetError("cell has no cloud journey target kind")
    execution = copy.deepcopy(template["execution"])
    authored = execution["datasource"]
    execution["datasource"] = {
        "name": authored["name"],
        **{f"{field}Env": name for field, name in DATASOURCE_ENV.items()},
        # RDS requires TLS; the server must not downgrade the journey connection.
        "sslRequired": True,
        "sslMode": "Require",
    }
    target = {
        "schemaVersion": 1,
        "id": cell,
        "kind": kind,
        "description": "Generated by e2e/cloud_journey.py for one cloud cell attempt. References only: "
                       "no credential, database host or login is written here.",
        "notes": "Externally provisioned cloud cell; the cloud harness owns teardown.",
        "adminPassword": {"env": ADMIN_ENV, "default": ""},
        "endpoints": copy.deepcopy(template["endpoints"]),
        "budgets": copy.deepcopy(template["budgets"]),
        "revisions": dict(REVISIONS),
        "principalSource": "cell-admin-api",
        "principals": {name: template["principals"][name] for name in MINTED_PRINCIPALS},
        "unavailablePrincipals": {
            "other-tenant": {"reason": OTHER_TENANT_REASON, "blockedBy": [OTHER_TENANT_BLOCKER]},
        },
        "replicaBaseUrl": (endpoint or "").rstrip("/"),
        "replicaTopology": dict(TOPOLOGIES[kind]),
        "execution": execution,
    }
    validate(target, template=template)
    return target


def _origin(url):
    parsed = urllib.parse.urlsplit(url or "")
    host = (parsed.hostname or "").lower()
    if (parsed.scheme not in ("https", "http") or not host or parsed.username or parsed.password
            or parsed.query or parsed.fragment or parsed.path not in ("", "/")):
        raise TargetError("replicaBaseUrl must be the bare cell origin")
    # Whether credentials may travel to it is decided by the one shared transport rule
    # (probes.credential_transport, honua-release#507), not by the target document.


def validate(target, *, template=None):
    """Fail closed on a cloud target that could leak, weaken or misdescribe the run."""
    kind = target.get("kind")
    if kind not in CLOUD_KINDS or kind_of(target.get("id")) != kind:
        raise TargetError("cloud target kind must match its aws-ecs/aws-serverless cell id")
    if target.get("adminPassword") != {"env": ADMIN_ENV, "default": ""}:
        raise TargetError("the bootstrap credential must be the cell's per-run reference with no default")
    if "compose" in target:
        raise TargetError("a cloud target never manages a compose stack")
    principals = target.get("principals")
    if not isinstance(principals, dict) or set(principals) != set(MINTED_PRINCIPALS):
        raise TargetError("cloud principals are exactly the four minted journey principals")
    if not all(isinstance(ref, str) and ENV_NAME.match(ref) for ref in principals.values()):
        raise TargetError("principals must be environment references, never values")
    if target.get("principalSource") != "cell-admin-api":
        raise TargetError("cloud principals are minted through the cell admin API")
    unavailable = target.get("unavailablePrincipals")
    if (not isinstance(unavailable, dict) or set(unavailable) != {"other-tenant"}
            or not unavailable["other-tenant"].get("reason")
            or not unavailable["other-tenant"].get("blockedBy")):
        raise TargetError("the second-tenant principal must be documented unavailable with a reason and blocker")
    _origin(target.get("replicaBaseUrl"))
    if target.get("replicaTopology") != TOPOLOGIES[kind]:
        raise TargetError("replicaTopology must name this kind's serving topology")
    execution = target.get("execution") or {}
    datasource = execution.get("datasource") or {}
    if datasource.get("sslRequired") is not True or datasource.get("sslMode") != "Require":
        raise TargetError("the cell datasource requires TLS (sslRequired, sslMode Require)")
    literal = set(DATASOURCE_ENV) & set(datasource)
    if literal:
        raise TargetError("datasource coordinates must be environment references: " + ", ".join(sorted(literal)))
    if {key: datasource.get(f"{key}Env") for key in DATASOURCE_ENV} != DATASOURCE_ENV:
        raise TargetError("datasource references must be the cell datasource environment names")
    upload = execution.get("upload") or {}
    path = HERE / str(upload.get("path", ""))
    if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != upload.get("sha256"):
        raise TargetError("upload fixture must be the committed, SHA-pinned journey source")
    if template is not None:
        authored = {key: value for key, value in template["execution"].items() if key != "datasource"}
        if {key: value for key, value in execution.items() if key != "datasource"} != authored:
            raise TargetError("cloud execution fixture must equal the authored local fixture")
    return target
