version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "16:00"
      timezone: Pacific/Honolulu
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
    rebase-strategy: auto

