"""Render customer compatibility documentation from a release lock, without certification inference."""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from sdk_baselines import SDK_COMPONENTS, check_component, content_digest, findings
from validate_platform_lock import validate

ROOT = Path(__file__).resolve().parents[1]


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def render(lock: dict) -> str:
    lines = [
        "# SDK and server compatibility", "",
        "<!-- Generated by tools/generate_compatibility_table.py; do not edit. -->", "",
        f"Platform: `{cell(lock.get('platform', {}).get('id', 'unqualified'))}`. "
        f"Lock canonical SHA-256: `{content_digest(lock)}`.", "",
        "Lock completeness: " + ("validated; certification still requires receipts." if validate(lock).ok else "**unqualified — incomplete draft; not a certified release lock.**"), "",
        "This table reports declared protocol requirements. A version floor is not a certified",
        "SDK/server pairing. Certification requires an exact artifact-pair receipt in the compatibility ledger.", "",
        "[Derivation rule](SDK-SERVER-BASELINE-RULE.md). Missing evidence is explicitly unqualified.", "",
        "| SDK / protocol | Locked artifact | Minimum server | Qualification |",
        "| --- | --- | --- | --- |",
    ]
    for name in SDK_COMPONENTS:
        component = lock.get("components", {}).get(name, {})
        artifacts = "; ".join(f"{a.get('coordinate', 'unqualified')} {a.get('version', 'unqualified')}" for a in component.get("artifacts", [])) or "source pin only"
        try:
            floor, qualification = check_component(component), "declared floor; pairing unqualified"
        except (ValueError, TypeError, KeyError, AttributeError) as exc:
            floor, qualification = "unqualified", str(exc)
        lines.append(f"| {cell(name)} | {cell(artifacts)} | {cell(floor)} | {cell(qualification)} |")
    lines += [
        "", "The JavaScript repository also owns `@honua/mcp-server`; its Honua attachment must",
        "bind the consumed SDK and MCP manifests. Standalone third-party protocol reads do not",
        "require a Honua Server. `geospatial-mcp` is the protocol specification, not an SDK binary.",
        "", "## UPGRADE EDGES", "",
        "| From server / schema | To server / schema | Supported edge | Previous server reads migrated schema / application rollback | Database rollback | Restore backup required | Evidence |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    # Until an edge has separate schema-read and database-recovery receipts, a generic
    # rollback pass cannot establish either capability. The empty row is an operator template.
    lines += [
        "| unqualified | unqualified | unqualified | unqualified | unqualified | unqualified | No qualified edge is pinned in this lock |",
        "", "Application rollback reinstalls the previous server against the migrated database.",
        "Database rollback restores the previous schema and data state. They require separate evidence.",
        "If the previous server cannot read the migrated schema and no verified database reverse",
        "migration exists, restoring a verified pre-upgrade backup is required to return to that server.",
        "A forward migration or a generic rollback receipt alone does not establish either rollback path.",
        "No supported upgrade edge is implied by adjacent version numbers or platform labels.", "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("lock", type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "docs/SDK-SERVER-COMPATIBILITY.md")
    parser.add_argument("--check", action="store_true", help="fail for stale output or any unqualified/disagreeing baseline")
    parser.add_argument("--check-output", action="store_true", help="check documentation freshness only; not a release qualification gate")
    args = parser.parse_args(argv)
    try:
        lock = yaml.safe_load(args.lock.read_text(encoding="utf-8"))
        if not isinstance(lock, dict) or lock.get("lockVersion") != "platform-lock.v1":
            raise ValueError("expected a platform-lock.v1 mapping")
        output = render(lock)
        if args.check or args.check_output:
            if not args.output.exists() or args.output.read_text(encoding="utf-8") != output:
                raise ValueError("compatibility table is stale; regenerate from this lock")
        else:
            args.output.write_text(output, encoding="utf-8", newline="\n")
        errors = findings(lock)
        if args.check and errors:
            raise ValueError("; ".join(errors))
        print("PASS: documentation matches lock" if args.check_output else ("UNQUALIFIED: table written; use --check for release qualification" if errors else "PASS: declared baselines match lock"))
        return 0
    except (OSError, ValueError, TypeError, yaml.YAMLError) as exc:
        print(f"BLOCKED: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
