"""Hand-authored terminal receipt fixtures; never generated by the checker/driver."""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest
import yaml
from jsonschema import Draft202012Validator, FormatChecker

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_journey_receipts as checker

NOW = datetime(2026, 10, 2, 20, 0, tzinfo=timezone.utc)
STAMP = "2026-10-02T19:59:00Z"
RUN = "12345"
RUN_ATTEMPT = "2"
CLIENTS = {name: {"package": package, "version": "2026.1.0-rc.3",
                  "integrity": "sha512-hand-built", "digest": None, "sourceSha": "a" * 40}
           for name, package in (("honua-sdk-js", "@honua/sdk"),
                                 ("honua-mcp-server", "@honua/mcp-server"))}
MANIFEST = {"platformRelease": "2026.1-rc.3", "clientArtifacts": CLIENTS,
            "components": {"honua-server": {"sha": "b" * 40,
                            "image": "ghcr.io/honua/server", "digest": "sha256:" + "c" * 64}}}
# Number, stage, command are written independently from the owned journey contract.
STAGES = [
    (1, "installed-client-handoff", "install exact manifest clients; verify readiness, identity, auth, profiles and tools/list"),
    (2, "credential-preflight", "honua admin apiKeys list/effective-permissions"),
    (3, "publish-service", "honua admin connection create/test; import; publish/configure layer and access policy"),
    (4, "style-render", "honua_get_style; honua_apply_style_preset; honua_render_map; validate decoded PNG"),
    (5, "bounded-gp", "discover/run geometry.buffer; wait/cancel canonical job; retain result"),
    (6, "durable-compositions", "create/mutate/validate/version map+dashboard; restart/reopen; compare hashes"),
    (7, "publication-proposal", "submit and poll durable AwaitingApproval proposal bound to item/version/hash"),
    (8, "separate-principal-approval", "honua admin operate approveOperationProposal --profile approver --yes; poll published URL"),
]


def receipt(cell):
    return {"schemaVersion": 1, "receiptSchema": "terminal-journey-receipt-v1",
            "evidenceKey": "release.e2e.terminal-zero-to-map", "generatedAt": STAMP,
            "mode": "live", "target": {"id": cell, "kind": "aws-ecs",
                "configPath": "target.json", "configSha256": "d" * 64},
            "status": "pass", "release": "2026.1-rc.3", "clientArtifacts": CLIENTS,
            "clientWorkspace": {"status": "pass", "source": "published-registry-bytes",
                "resolved": [{"name": "honua-sdk-js", "package": "@honua/sdk",
                              "version": "2026.1.0-rc.3", "ecosystem": "npm",
                              "integrityVerified": True, "tarballSha256": "e" * 64,
                              "bin": {"honua": "cli.js"}}],
                "commandSurface": [], "installNotes": []},
            "server": {"sourceSha": "b" * 40, "image": "ghcr.io/honua/server@sha256:" + "c" * 64},
            "fixtureRevision": "fixture-v1", "configRevision": "config-v1",
            "authPolicyRevision": "auth-v1", "roster": {"status": "pass"},
            "stages": [{"number": number, "stage": stage, "command": command,
                "status": "pass", "blockedBy": [],
                "checks": [{"id": "probe", "kind": "mcp-tool", "invocation": command,
                            "status": "pass", "detail": "observed"}],
                "operationId": "op", "operationInstanceId": "opinst", "correlationId": "corr",
                "auditId": "audit", "proposalId": "proposal", "jobId": "job", "resourceUri": "honua://jobs/job",
                "jobStatus": "accepted", "jobCreatedAt": STAMP, "policyDecisionId": None, "approvalId": None,
                "actuatorId": None, "verificationId": None,
                "evidence": {"uri": "urn:hand-built:observation", "source": "live-aws-ecs",
                             "freshness": "verified-current", "completeness": "complete",
                             "observedAt": STAMP}} for number, stage, command in STAGES],
            "notices": [], "linkedEvidence": {"awsProvisioning": "honua-release#129",
                                               "genuineModelCanary": "honua-release#161"}}


def failed_receipt(cell):
    result = receipt(cell)
    result["status"] = "fail"
    result["stages"][0]["status"] = "fail"
    result["stages"][0]["checks"][0]["status"] = "fail"
    result["failure"] = {"number": 1, "stage": STAGES[0][1], "command": STAGES[0][2],
                         "check": "probe", "detail": "failed handoff"}
    return result


class Intake:
    def __init__(self, root):
        self.root = root
        self.candidate = root / "candidate.yaml"
        self.candidate.write_text(yaml.safe_dump(MANIFEST))
        self.digest = hashlib.sha256(self.candidate.read_bytes()).hexdigest()
        for cell in checker.GA_CELLS:
            self.write(cell)

    def directory(self, cell):
        return self.root / ("e2e-cloud-aws-gate-report-" + cell.replace("/", "-"))

    def write(self, cell, receipts=None, *, drivers=None, attributions=None):
        directory = self.directory(cell)
        directory.mkdir(exist_ok=True)
        attempts = []
        for i, value in enumerate(receipts or [receipt(cell)], 1):
            path = directory / "cloud-evidence" / RUN / RUN_ATTEMPT / cell / f"receipt-{i}.json"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(value))
            record = {"number": i, "cell": cell, "runId": RUN, "runAttempt": RUN_ATTEMPT,
                      "candidateDigest": self.digest, "receipt": str(path.relative_to(directory)),
                      "receiptSha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                      "failureAttribution": (attributions[i-1] if attributions else
                                             "infrastructure" if value["status"] != "pass" else None)}
            if drivers:
                record["driver"] = drivers[i-1]
            attempts.append(record)
        report = {"cell": cell, "status": "pass", "journeyAttempts": attempts}
        self.save(cell, report)
        return report

    def save(self, cell, report):
        (self.directory(cell) / "gate-report-cloud.json").write_text(json.dumps(report))

    def evaluate(self):
        return checker.evaluate(self.root, self.candidate, self.digest, RUN, RUN_ATTEMPT, at=NOW)


@pytest.fixture
def intake(tmp_path):
    return Intake(tmp_path)


def assert_red(intake, reason):
    report = intake.evaluate()
    assert report["status"] == report["overallStatus"] == "fail"
    assert reason in report["why"]


def test_hand_built_fixtures_validate_against_owned_schema():
    validator = Draft202012Validator(checker.load_json(checker.ROOT /
        "certification/terminal-journey/receipt.schema.json"), format_checker=FormatChecker())
    for cell in checker.GA_CELLS:
        validator.validate(receipt(cell))
        validator.validate(failed_receipt(cell))


def test_all_four_exact_candidate_cells_pass_and_record_driver(intake):
    intake.write(checker.GA_CELLS[0], drivers=["genuine-model"])
    result = intake.evaluate()
    assert result["status"] == "pass"
    ga = [r for r in result["cells"] if r["counted"]]
    assert len(ga) == 4
    assert ga[0]["drivers"] == ["genuine-model"]
    assert ga[0]["attempts"][0]["completedAt"] == STAMP
    assert ga[1]["drivers"] == ["deterministic"]
    assert result["gates"][0]["decided"] == "pass"


@pytest.mark.parametrize("attribution", ["model", "infrastructure"])
def test_attributed_failure_then_second_attempt_passes(intake, attribution):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [failed_receipt(cell), receipt(cell)], attributions=[attribution, None])
    result = intake.evaluate()
    assert result["status"] == "pass"
    assert result["cells"][0]["attempts"][0]["failureAttribution"] == attribution


@pytest.mark.parametrize("cell", checker.GA_CELLS)
def test_missing_ga_cell_is_red(intake, cell):
    (intake.directory(cell) / "gate-report-cloud.json").unlink()
    assert_red(intake, "missing cell receipt")


@pytest.mark.parametrize("status", ["skipped", "blocked", "fail"])
def test_nonpassing_cell_report_is_red(intake, status):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell)
    report["status"] = status
    intake.save(cell, report)
    assert_red(intake, "cell skipped/failed")


def test_skipped_receipt_is_red(intake):
    cell = checker.GA_CELLS[0]
    data = receipt(cell)
    data["status"] = "skipped"
    intake.write(cell, [data])
    assert_red(intake, "invalid or skipped")


@pytest.mark.parametrize("stamp", ["2026-09-30T19:59:00Z", "2026-10-02T20:01:00Z"])
def test_stale_or_future_receipt_is_red(intake, stamp):
    cell = checker.GA_CELLS[0]
    data = receipt(cell)
    data["generatedAt"] = stamp
    intake.write(cell, [data])
    assert_red(intake, "stale or future")


@pytest.mark.parametrize("field,value", [("candidateDigest", "f" * 64), ("runId", "999"),
                                           ("runAttempt", "1"), ("cell", "aws-eks/redis-off")])
def test_wrong_attempt_binding_is_red(intake, field, value):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell)
    report["journeyAttempts"][0][field] = value
    intake.save(cell, report)
    assert_red(intake, "wrong candidate, run or cell")


@pytest.mark.parametrize("field", ["release", "server", "clientArtifacts", "target"])
def test_wrong_receipt_candidate_or_cell_is_red(intake, field):
    cell = checker.GA_CELLS[0]
    data = receipt(cell)
    if field == "release":
        data[field] = "2026.1-rc.2"
    elif field == "server":
        data[field]["sourceSha"] = "f" * 40
    elif field == "clientArtifacts":
        data[field] = json.loads(json.dumps(CLIENTS))
        data[field]["honua-sdk-js"]["version"] = "old"
    else:
        data[field]["id"] = checker.GA_CELLS[1]
    intake.write(cell, [data])
    assert_red(intake, "wrong candidate or receipt cell")


def test_third_attempt_cannot_recover_cell(intake):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [failed_receipt(cell), failed_receipt(cell), receipt(cell)])
    assert_red(intake, "within 2 attempts")


def test_two_failures_are_red(intake):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [failed_receipt(cell), failed_receipt(cell)])
    assert_red(intake, "missing a passing receipt")


@pytest.mark.parametrize("numbers", [[], [2], [1, 3], [1, 1], [True]])
def test_every_attempt_must_be_recorded(intake, numbers):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell, [failed_receipt(cell), receipt(cell)])
    report["journeyAttempts"] = [{**report["journeyAttempts"][-1], "number": n} for n in numbers]
    intake.save(cell, report)
    assert_red(intake, "every attempt must be recorded")


def test_attempt_after_pass_is_red(intake):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [receipt(cell), receipt(cell)])
    assert_red(intake, "after passing receipt")


def test_unrecorded_failed_receipt_cannot_be_hidden(intake):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell, [failed_receipt(cell), receipt(cell)])
    report["journeyAttempts"] = [{**report["journeyAttempts"][1], "number": 1}]
    intake.save(cell, report)
    assert_red(intake, "omitted from recorded attempt history")


def test_failed_cell_still_reports_attempt_driver_and_attribution(intake):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [failed_receipt(cell)], drivers=["genuine-model"], attributions=["model"])
    result = intake.evaluate()
    row = result["cells"][0]
    assert row["status"] == "fail" and row["drivers"] == ["genuine-model"]
    assert row["attempts"][0]["failureAttribution"] == "model"


@pytest.mark.parametrize("attribution", [None, "unknown", "", False])
def test_unattributed_failure_cannot_be_hidden_by_pass(intake, attribution):
    cell = checker.GA_CELLS[0]
    intake.write(cell, [failed_receipt(cell), receipt(cell)], attributions=[attribution, None])
    assert_red(intake, "unattributed")


def test_unknown_driver_is_red(intake):
    intake.write(checker.GA_CELLS[0], drivers=["replay"])
    assert_red(intake, "unknown journey driver")


@pytest.mark.parametrize("defect", ["stage", "check", "freshness", "completeness", "observedAt", "source", "roster", "mode"])
def test_nonobserved_or_incomplete_journey_is_red(intake, defect):
    cell = checker.GA_CELLS[0]
    data = receipt(cell)
    stage = data["stages"][0]
    if defect == "stage":
        data["stages"].pop()
    elif defect == "check":
        stage["checks"] = []
    elif defect == "roster":
        data["roster"]["status"] = "blocked"
    elif defect == "mode":
        data["mode"] = "build"
    else:
        stage["evidence"][defect] = {"freshness": "stale", "completeness": "partial",
            "observedAt": "2026-09-30T19:59:00Z", "source": "live-local-docker"}[defect]
    intake.write(cell, [data])
    assert intake.evaluate()["status"] == "fail"


def test_duplicate_stage_cannot_replace_missing_stage(intake):
    cell = checker.GA_CELLS[0]
    data = receipt(cell)
    data["stages"][1]["number"] = 1
    intake.write(cell, [data])
    assert_red(intake, "every pinned journey stage")


@pytest.mark.parametrize("defect", ["missing", "hash", "escape", "absolute", "symlink", "malformed"])
def test_untrusted_receipt_file_is_red(intake, defect, tmp_path):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell)
    record = report["journeyAttempts"][0]
    path = intake.directory(cell) / record["receipt"]
    if defect == "missing":
        path.unlink()
    elif defect == "hash":
        record["receiptSha256"] = "0" * 64
    elif defect == "escape":
        record["receipt"] = "../receipt.json"
    elif defect == "absolute":
        record["receipt"] = str(path)
    elif defect == "symlink":
        outside = tmp_path / "outside.json"
        outside.write_bytes(path.read_bytes())
        path.unlink()
        path.symlink_to(outside)
    else:
        path.write_text('{"bad": true, "bad": false}')
        record["receiptSha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
    intake.save(cell, report)
    assert intake.evaluate()["status"] == "fail"


def test_duplicate_ga_report_is_red(intake):
    cell = checker.GA_CELLS[0]
    directory = intake.root / "duplicate"
    directory.mkdir()
    (directory / "gate-report-cloud.json").write_bytes((intake.directory(cell) / "gate-report-cloud.json").read_bytes())
    assert_red(intake, "duplicate cell reports")


def test_ga_cannot_self_label_as_preview(intake):
    cell = checker.GA_CELLS[0]
    report = intake.write(cell)
    report.update(evidenceTier="Preview", status="skipped")
    intake.save(cell, report)
    assert intake.evaluate()["status"] == "fail"


@pytest.mark.parametrize("status", ["pass", "fail", "blocked", "skipped", "corrupt"])
def test_preview_never_blocks_or_counts(intake, status):
    for cell in checker.PREVIEW_CELLS:
        report = intake.write(cell)
        report["status"] = status
        intake.save(cell, report)
        if status == "corrupt":
            (intake.directory(cell) / "gate-report-cloud.json").write_text("{invalid")
    result = intake.evaluate()
    assert result["status"] == "pass"
    preview = [r for r in result["cells"] if r["evidenceTier"] == "Preview"]
    assert len(preview) == 4 and not any(r["counted"] for r in preview)


def test_preview_pass_cannot_replace_ga_receipt(intake):
    for cell in checker.GA_CELLS:
        (intake.directory(cell) / "gate-report-cloud.json").unlink()
    for cell in checker.PREVIEW_CELLS:
        intake.write(cell)
    assert_red(intake, "missing cell receipt")


def test_preview_report_retains_only_allowlisted_metadata(intake):
    cell = checker.PREVIEW_CELLS[0]
    report = intake.write(cell)
    report["rawToolOutput"] = "sensitive-value"
    report["endpoint"] = "https://example.invalid/?token=sensitive-value"
    intake.save(cell, report)
    result = intake.evaluate()
    assert result["status"] == "pass"
    assert "sensitive-value" not in json.dumps(result)


def test_candidate_bytes_must_match_independent_digest(intake):
    intake.candidate.write_text(intake.candidate.read_text() + "\n")
    assert_red(intake, "invalid candidate identity")


def test_malformed_ga_report_is_red(intake):
    (intake.directory(checker.GA_CELLS[0]) / "gate-report-cloud.json").write_text("{invalid")
    assert_red(intake, "invalid cell report")


def test_cli_writes_failure_report_and_exits_nonzero(tmp_path):
    candidate = tmp_path / "candidate.yaml"
    candidate.write_text(yaml.safe_dump(MANIFEST))
    output = tmp_path / "out/report.json"
    result = subprocess.run([sys.executable, str(Path(checker.__file__)), "--receipts", str(tmp_path),
        "--candidate", str(candidate), "--candidate-digest", hashlib.sha256(candidate.read_bytes()).hexdigest(),
        "--run-id", RUN, "--run-attempt", RUN_ATTEMPT, "--report", str(output)], capture_output=True)
    assert result.returncode == 1
    assert json.loads(output.read_text())["overallStatus"] == "fail"


def test_reusable_workflow_downloads_named_run_and_enforces_report():
    workflow = yaml.safe_load((checker.ROOT / ".github/workflows/gate-journey.yml").read_text())
    call = workflow[True]["workflow_call"]
    assert call["inputs"]["receipts_run_id"]["required"]
    assert call["inputs"]["candidate_digest"]["required"]
    steps = workflow["jobs"]["journey"]["steps"]
    download = next(s for s in steps if s.get("name") == "Download per-cell receipts from the named run")
    assert download["with"]["run-id"] == "${{ inputs.receipts_run_id }}"
    assert download["with"]["merge-multiple"] is False
    assert download["with"]["pattern"] == "e2e-cloud-aws-gate-report-*"
    evaluate = next(s for s in steps if s.get("id") == "check")
    assert evaluate["if"] == "always()"
    assert '--candidate-digest "$CANDIDATE_DIGEST"' in evaluate["run"]
    assert steps[-1]["if"] == "always()"
    assert steps[-1]["run"] == 'test "$STATUS" = pass'
    assert not any(s.get("continue-on-error", False) for s in steps)


@pytest.mark.parametrize("override", [{"head_branch": "feature"}, {"event": "pull_request"},
    {"path": ".github/workflows/untrusted.yml"}, {"id": 999}, {"run_attempt": 1}])
def test_workflow_refuses_untrusted_producer_run(tmp_path, override):
    workflow = yaml.safe_load((checker.ROOT / ".github/workflows/gate-journey.yml").read_text())
    step = next(s for s in workflow["jobs"]["journey"]["steps"]
                if s.get("name") == "Verify the receipt producer is a trunk workflow run")
    query = step["run"].split("jq -e", 1)[1].split("'", 2)[1]
    run = {"id": int(RUN), "run_attempt": int(RUN_ATTEMPT), "head_branch": "trunk",
           "event": "schedule", "path": ".github/workflows/e2e-cloud-aws.yml"}
    import shutil
    if shutil.which("jq") is None:
        pytest.fail("jq is required to verify the workflow's producer trust predicate")
    accepted = subprocess.run(["jq", "-e", "--arg", "id", RUN, "--arg", "attempt", RUN_ATTEMPT,
                               query], input=json.dumps(run), text=True, capture_output=True)
    assert accepted.returncode == 0
    run.update(override)
    refused = subprocess.run(["jq", "-e", "--arg", "id", RUN, "--arg", "attempt", RUN_ATTEMPT,
                              query], input=json.dumps(run), text=True, capture_output=True)
    assert refused.returncode != 0
