name: Commit hygiene

on:
  pull_request:

permissions:
  contents: read

jobs:
  commit-hygiene:
    uses: honua-io/.github/.github/workflows/commit-hygiene.yml@3871970fac013313981a9c90feeaa0e275617abb # v1.0.0
